name: Format suggestions

on:
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1
      - name: Install & run JuliaFormatter
        shell: julia --color=yes {0}
        run: |
          using Pkg
          Pkg.add("JuliaFormatter")
          using JuliaFormatter
          # HACK: as-of 2023-12-18, it seems that _two_ formatting passes are sometimes
          #   required to ensure subsequent formattings have no effect.
          was_already_formatted = format("."; verbose=true)
          format("."; verbose=true)
          exit(was_already_formatted ? 0 : 42)
